---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.1.0"
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-xml
      - id: end-of-file-fixer
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - id: prettier
        name: Apply Code Formatting
